package br.com.furb.tagarela.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SYMBOL_PLAN.
 */
public class SymbolPlan {

    private Integer serverID;
    private Integer planID;
    private Integer symbolID;
    private Integer position;

    public SymbolPlan() {
    }

    public SymbolPlan(Integer serverID, Integer planID, Integer symbolID, Integer position) {
        this.serverID = serverID;
        this.planID = planID;
        this.symbolID = symbolID;
        this.position = position;
    }

    public Integer getServerID() {
        return serverID;
    }

    public void setServerID(Integer serverID) {
        this.serverID = serverID;
    }

    public Integer getPlanID() {
        return planID;
    }

    public void setPlanID(Integer planID) {
        this.planID = planID;
    }

    public Integer getSymbolID() {
        return symbolID;
    }

    public void setSymbolID(Integer symbolID) {
        this.symbolID = symbolID;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

}
